### ISSUE TITLE
Error when running a job

### ISSUE THREAD

**Issue by fxkim** [Microsoft/MCW-Big-Compute#14]
Hi when I try to run a job (Exercice #3 Task#2)
with the the command: 
`sudo az batch job create --template ~/work/job.json --account-name mybatchaccount --account-endpoint mybatchdemo.westeurope.batch.azure.com
`

I get the following error:
```
Unable to deserialize to ExtendedJobParameter: Unable to deserialize {'blob_source': '{url}', 'file_path': '{fileName}', 'file_mode': None, 'source': None} into model <class 'azext.batch.models.extended_resource_file.ExtendedResourceFile'>. __init__() takes 1 positional argument but 4 were given
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1397, in _instantiate_model
    response_obj = response(**kwargs)
  File "/home/admindev/.azure/cliextensions/azure-batch-cli-extensions/azext/batch/models/extended_resource_file.py", line 46, in __init__
    super(ExtendedResourceFile, self).__init__(blob_source, file_path, file_mode)
TypeError: __init__() takes 1 positional argument but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admindev/.azure/cliextensions/azure-batch-cli-extensions/azext/batch/operations/job_operations.py", line 81, in jobparameter_from_json
    job = models.ExtendedJobParameter.from_dict(json_data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 318, in from_dict
    return deserializer(cls.__name__, data, content_type=content_type)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1230, in __call__
    return self._deserialize(target_obj, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1296, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1458, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1296, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1458, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1296, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1445, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1476, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1476, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1458, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1303, in _deserialize
    return self._instantiate_model(response, d_attrs, additional_properties)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1406, in _instantiate_model
    raise DeserializationError(msg + str(err))
msrest.exceptions.DeserializationError: Unable to deserialize {'blob_source': '{url}', 'file_path': '{fileName}', 'file_mode': None, 'source': None} into model <class 'azext.batch.models.extended_resource_file.ExtendedResourceFile'>. __init__() takes 1 positional argument but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/interactive/azclishell/app.py", line 659, in cli_execute
    result = invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    cmd.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/batch/_exception_handler.py", line 30, in batch_exception_handler
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 346, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/home/admindev/.azure/cliextensions/azure-batch-cli-extensions/azext_batch/custom.py", line 144, in create_job
    job = ExtendedJobOperations.jobparameter_from_json(json_obj)
  File "/home/admindev/.azure/cliextensions/azure-batch-cli-extensions/azext/batch/operations/job_operations.py", line 86, in jobparameter_from_json
    raise ValueError("Unable to deserialize to {}: {}".format(result, exp))
ValueError: Unable to deserialize to ExtendedJobParameter: Unable to deserialize {'blob_source': '{url}', 'file_path': '{fileName}', 'file_mode': None, 'source': None} into model <class 'azext.batch.models.extended_resource_file.ExtendedResourceFile'>. __init__() takes 1 positional argument but 4 were given

```

**Comment by DawnmarieDesJardins** [comment]
Hey Kyle!  Can you please take a look and help fxkim?  If it's something that needs correcting, I'm assuming it was caught in the Sept test/fix that on my plate to QC?  Thank you!

**Comment by kylebunting** [comment]
Will do. 

Kyle

**Comment by kylebunting** [comment]
@fxkim, I am able to complete this step successfully. Looking at your sudo command above, I noticed that your template location is listed as `~/work/job.json`. Would it be possible for you to try creating and running the job.json file directly in the samples directory you created for storing the sample video files? Also, please ensure you replace batchAccountName with the name of the batch account you created.

**Comment by kylebunting** [comment]
The issue was an entry error in the pool.json file, and has been resolved.
